### ISSUE TITLE
Failure to Instantiate chaincode due to DNS lookup failure

### ISSUE THREAD

**Issue by tballast** [APGGroeiFabriek/PIVT#1]
When attempting to [instantiate the chaincodes](https://github.com/APGGroeiFabriek/PIVT#installing-chaincodes), I am running into the following issue:

```
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/fabric-shim failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-11T12_27_09_181Z-debug.log
```

After looking around, this is a DNS timeout issue. Perhaps this has something to do with the fact that the instantiation creates a docker container, but then the two containers are unable to speak with one another? 

The closest thing to a solution I have found is [this](https://hackernoon.com/how-to-deploy-hyperledger-fabric-on-kubernetes-1-a2ceb3ada078) in the "Work around the chaincode sandbox" section. 

Perhaps this isn't an "Issue", however I am unable to get past it at the moment. 

I am using a cluster created with eksctl on AWS. The cluster was created with the following command: `eksctl create cluster --name=hlf --ssh-access --ssh-public-key=mykey`

**Comment by raftAtGit** [comment]
Weird, never saw this before! Please first check:

1. If your pods can access to internet
2. If so, maybe this is a temporary network issue, trying running it one more time
3. Maybe pods have internet access but not the containers created via host's (VM's) Docker socket? Unlikely but may worth checking
4. I dont know :/

I've seen instantiation failed before, possibly due to a communication failure between pod and the chaincode container, but setting `CORE_PEER_ADDRESSAUTODETECT=true `in peers effectively solved this

**Comment by tballast** [comment]
Ok, yea I think that it might be point 3. 

I tried sshing in a running node, and then I just launched a docker container using:

`docker run -it alpine sh`

which launched a container for me and from within it I wasn't able to do resolve anything with DNS. Furthremore, I wasn't able to reach the outside network with something like `ping 8.8.8.8` or `wget example.com` either. 

Any ideas how to start solving that?

**Comment by raftAtGit** [comment]
I guess I will start with comparing K8S created containers with plain ones with Docker inspect. That might give a clue. After that possibly/hopefully you can solve this by modifying Docker daemon settings.

https://odino.org/cannot-connect-to-the-internet-from-your-docker-containers/

Please share your experience if you solve this :)

**Comment by tballast** [comment]
Still working on it, but I'll share progress in case someone else sees and has an idea:

Within the EC2 instances that are being used as nodes in my cluster, the `/etc/docker/daemon.json` file had the line `"bridge": "none"`, and because of this whenever a container is created with the local docker host, there is no bridged connection to the hosts network, so it can't call out into the internet. 

starting something like `docker run -it --network=host alpine sh` will allow you to reach the internet though.

**Comment by raftAtGit** [comment]
I guess if you remove that line `"bridge": "none"` and restart Docker daemon possibly your issue will be resolved. In Azure AKS that line doesnt exist, also doesnt exist in default `/etc/docker/daemon.json` file.

I'm also guessing this is one extra security step by AWS. Sounds like AWS :)

**Comment by tballast** [comment]
Fixed it!

**Main Problem**: The bridge network for docker is disabled by default on worker nodes that are spun up by EKS. 
**Solution**: Re-enable the bridge network. 

So, this is specific to AWS (and EKS as that). When a worker node is created by EKS there is a script provided in the UserData of the container that is run on bootup, there are ways that you can provide arguments to this script as well. I believe that this could also be solved by providing the `--enable-docker-bridge true` flag as a BootstrapParameter for your Stack, if you create it through the AWS Management Console (see [here](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html) for more information), however I was using [eksctl](https://github.com/weaveworks/eksctl) and don't know of a way to provide that parameter with this tool, so I instead went to the [bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh) script and at the end there are a few lines of code for enabling the bridge network again, so I ran those manually on each worker.

```
# Enabling the docker bridge network. We have to disable live-restore as it
# prevents docker from recreating the default bridge network on restart
echo "$(jq '.bridge="docker0" | ."live-restore"=false' /etc/docker/daemon.json)" > /etc/docker/daemon.json
systemctl restart docker
systemctl daemon-reload
```

Afterwards, the chaincode instantiates without a problem. 


For the record, here's what my daemon.json file looks like on the ec2 worker node. 
```
[ec2-user@ip-192-168-64-214 ~]$ cat /etc/docker/daemon.json 
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "10"
  },
  "live-restore": false,
  "max-concurrent-downloads": 10,
  "bridge": "docker0"
}
```

**Comment by raftAtGit** [comment]
Awesome!

**Comment by abhisamant7** [comment]
Hi ,
I have tried above step mentioned by Tyler but when I am trying to implement the node.js based chaincode still getting error(mention below). please see the argo log of pods as below 
```
abhi@abhi-Vostro-3478:~/Documents/PIVT/fabric-kube$ argo logs hlf-chaincodes-vvpcw-3334482624
Chaincode very-simple version 1.0 is not instantiated on channel common 
-- result is: 99
-- Chaincode very-simple version 1.0 is not instantiated on channel common, will check another version..
Chaincode very-simple is not instantiated on channel common 
-- result is: 99
-- Chaincode very-simple is not instantiated on channel common, will instantiate..
2020-01-08 20:48:36.682 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2020-01-08 20:48:36.682 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: Failed to generate platform-specific docker build: Error executing build: API error (404): network bridge not found ""
```
Please suggest how to solve the error 
Thanks in advance

**Comment by marcelloromani** [comment]
@abhisamant7 Are you on AWS (more specifically EKS)? See comment above by tballast

> Main Problem: The bridge network for docker is disabled by default on worker nodes that are spun up by EKS.

**Comment by abhisamant7** [comment]
> @abhisamant7 Are you on AWS (more specifically EKS)? See comment above by tballast
> 
> > Main Problem: The bridge network for docker is disabled by default on worker nodes that are spun up by EKS.

Actually I gone though above setp which Tyler mentioned, however still getting issue with  

> Fixed it!
> 
> **Main Problem**: The bridge network for docker is disabled by default on worker nodes that are spun up by EKS.
> **Solution**: Re-enable the bridge network.
> 
> So, this is specific to AWS (and EKS as that). When a worker node is created by EKS there is a script provided in the UserData of the container that is run on bootup, there are ways that you can provide arguments to this script as well. I believe that this could also be solved by providing the `--enable-docker-bridge true` flag as a BootstrapParameter for your Stack, if you create it through the AWS Management Console (see [here](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html) for more information), however I was using [eksctl](https://github.com/weaveworks/eksctl) and don't know of a way to provide that parameter with this tool, so I instead went to the [bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh) script and at the end there are a few lines of code for enabling the bridge network again, so I ran those manually on each worker.
> 
> ```
> # Enabling the docker bridge network. We have to disable live-restore as it
> # prevents docker from recreating the default bridge network on restart
> echo "$(jq '.bridge="docker0" | ."live-restore"=false' /etc/docker/daemon.json)" > /etc/docker/daemon.json
> systemctl restart docker
> systemctl daemon-reload
> ```
> 
> Afterwards, the chaincode instantiates without a problem.
> 
> For the record, here's what my daemon.json file looks like on the ec2 worker node.
> 
> ```
> [ec2-user@ip-192-168-64-214 ~]$ cat /etc/docker/daemon.json 
> {
>   "log-driver": "json-file",
>   "log-opts": {
>     "max-size": "10m",
>     "max-file": "10"
>   },
>   "live-restore": false,
>   "max-concurrent-downloads": 10,
>   "bridge": "docker0"
> }
> ```

I have gone though above step as mentioned by Tyler still getting same issue which I mention previous comment. Please see my daemon.json file looks like on the ec2 worker node.

```
[ec2-user@ip-192-168-156-223 ~]$ cat /etc/docker/daemon.json 
{
  "bridge": "docker0",
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "10"
  },
  "live-restore": false,
  "max-concurrent-downloads": 10
}
{
  "insecure-registries": [
    "192.168.0.5:5001"
  ],
  "bridge": "docker0",
  "live-restore": false
}
```

**Comment by ginsctw** [comment]
@abhisamant7  I am also facing the same issue.  I am using AWS EKS and executed below commands in all the worker node.

`echo "$(jq '.bridge="docker0" | ."live-restore"=false' /etc/docker/daemon.json)" > /etc/docker/daemon.json
systemctl restart docker
systemctl daemon-reload`

Now when I try to instantiate the chaincode I am getting below error.

"Failed to instantiate the chaincode. cause:instantiate proposal resulted in an error :: Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error executing build: API error (404): network bridge not found \"\"". 

Could you please let me know if you managed to solve the issue.

**Comment by chainhead** [comment]
@tballast  

> ...however I was using eksctl and don't know of a way to provide that parameter with this tool,...

There are [parameters](https://eksctl.io/usage/schema/#nodeGroups-preBootstrapCommands) in the config file of `eksctl` that can be used to control the boot strapping - `preBootstrapCommands` and `overrideBootstrapCommands`. Might want to try them out.
